[programs.localnet]
doorman = "D8bTW1sgKaSki1TBUwxarPySLp3TNVgB2bwRVbbTLYeV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
#wallet = "~/.config/solana/id2.json"

[scripts]
test = "mocha -t 1000000 tests/"
initialize = "node -r dotenv/config scripts/initialize.js dotenv_config_path=./app/.env"
show-config = "node -r dotenv/config scripts/show_config.js dotenv_config_path=./app/.env"
update-config = "node -r dotenv/config scripts/update_config.js dotenv_config_path=./app/.env"
test-purchase = "node -r dotenv/config scripts/test_purchase.js dotenv_config_path=./app/.env"
add-address = "node -r dotenv/config scripts/add_address.js dotenv_config_path=./app/.env"
